export const books = [
  {
   id: 1,
   img: "https://m.media-amazon.com/images/I/A1nR6LZWasL._SL1500_.jpg",
   title: "Fantastic Beasts and Where to Find Them",
   author: "J.K. Reilly",
   price: "$335",
   genre: "supernatural"
 },
 {
   id: 2,
   img: "https://m.media-amazon.com/images/I/714+tgyHDRL._SY522_.jpg",
   title: "Data Structures And Algorithms ",
   author: "Narasimha Karumanchi",
   price: "$749",
   genre: "cse",
 },
 { 
   id: 3,
   img: "https://m.media-amazon.com/images/I/81FZNcCGP-L._SY522_.jpg",
   title: "When Love Came Calling ",
   author: "Preeti Shenoy",
   price: "$1839",
   genre: "romcom"
 },
 {
  id: 4,
  img: "https://m.media-amazon.com/images/I/51uGVzNXipL._SY445_SX342_.jpg",
  title: "Harry Potter and the Philosopher's stone",
  author: "J.K. Rowling",
  price: "$68",
  genre: "supernatural",
 },
 {
   id: 5,
   img: "https://m.media-amazon.com/images/I/61o-1+AF3JS._SL1254_.jpg",
   title: "Fundamentals of Cryptography",
   author: " Duncan Buell ",
   price: "$119",
   genre: "cse"
 },
 { 
  id: 6,
  img: "https://m.media-amazon.com/images/I/71+LrbyUEDL._SL1500_.jpg",
  title: "How to Stop Worrying and Start Living",
  author: "Dale Carnegie",
  price: "$500",
  genre: "motivation"
 },
 {
  id: 7,
  img: "https://m.media-amazon.com/images/I/71IobR8EclL._SL1400_.jpg",
  title: "Wuthering Heights",
  author: "Emily Bronte",
  price: "$45.10",
  genre: "motivation",
 },
 {
  id: 8,
  img: "https://m.media-amazon.com/images/I/81aQWGD94ML._SY522_.jpg",
  title: "Cryptography & Network Security",
  author: " Tatiana Hodorogea",
  price: "$18,450",
  genre: "security",
 },
 {
  id: 9,
  img: "https://m.media-amazon.com/images/I/71LtJmAsv-L._SL1000_.jpg",
  title: "The Memoirs of Sherlock Holmes",
  author: "Sir Arthur Conan Doyle",
  price: "$20.00",
  genre: "thriller"
 },
 {
  id: 10,
  img: "https://m.media-amazon.com/images/I/712UNxm026L._SL1000_.jpg",
  title: "The Special And The General Theory",
  author: " Albert Einstein",
  price: "$1039",
  genre: "astronomy"
 },
 {
  id: 11,
  img: "https://m.media-amazon.com/images/I/71Hpf3S5gmL._SL1360_.jpg",
  title: "Astronomy For Beginners",
  author: "Sally R. Ball",
  price: "$569",
  genre: "astronomy",
 },
 {
  id: 12,
  img: "https://m.media-amazon.com/images/I/71ZsPM2RRBL._SL1500_.jpg",
  title: "Stars Shine Only in the Darkness",
  author: "Haris AdiWaid",
  price: "$110",
  genre: "motivation"
 },
 {
   id: 13,
   img: "https://m.media-amazon.com/images/I/81HquwFEPgL._SL1500_.jpg",
   title: "You are the Best Friend: A True Love Story",
   author: "Ajay K Pandey",
   price: "$76",
   genre: "romantic",
 },
 {
  id: 14,
  img: "https://m.media-amazon.com/images/I/81VngMSTk6L._SL1500_.jpg",
  title: "Between the Dawn and Day: Galaxy Girl Book Two",
  author: "Kate Christie",
  price: "$230",
  genre: "romantic",
 },
 {
  id: 15,
  img: "https://m.media-amazon.com/images/I/61ih2avnXLL._SL1360_.jpg",
  title: "The Diary of My Love",
  author: "Deesha Sangani",
  price: "$150.87",
  genre: "romantic",
 },
 {
  id: 16,
  img: "https://m.media-amazon.com/images/I/71ZsPM2RRBL._SL1500_.jpg",
  title: "You Last Step To Fast Financial Freedom",
  author: "Aryan Chaudhary",
  price: "$100",
  genre: "finance",
 },
 {
   id: 17,
   img: "https://m.media-amazon.com/images/I/51vT3X2tdtL._SY522_.jpg",
   title: "Computer Networking A Top Down Approach",
   author: "Thomas Sch",
   price: "$105",
   genre: "security",
 },
 {
  id: 18,
  img: "https://m.media-amazon.com/images/I/814RhA2+2GL._SY522_.jpg",
  title: "A Touch of Eternity",
  author: "Durjoy Dutta",
  price: "$340",
  genre: "romance",
 },
 {
  id: 19,
  img: "https://m.media-amazon.com/images/I/71vfo4cJCjL._SL1500_.jpg",
  title: "The Theory of Everything",
  author: "Stephen W Hawking",
  price: "$290",
  genre: "universe",
 },
 {
  id: 20,
  img: "https://m.media-amazon.com/images/I/71gtWVKJ7kL._SL1360_.jpg",
  title: "A Girl to Remember",
  author: "Ajay K Pandey",
  price: "$832",
  genre: "romance",
 },
 {
  id: 21,
  img: "https://m.media-amazon.com/images/I/71baLm1F++L._SL1500_.jpg",
  title: "The Temporary Roomie",
  author: "Sarah Adams",
  price: "$67",
  genre: "comedy",
 },
 {
  id: 22,
  img: "https://m.media-amazon.com/images/I/71J7XjS8TrL._SL1500_.jpg",
  title: "The Living Mountain",
  author: "Amitav Ghosh",
  price: "$223",
  genre: "motivation",
 },
 {
  id: 23,
  img: "https://m.media-amazon.com/images/I/71zTHzSnRGL._SY522_.jpg",
  title: "Data Analytics using Python",
  author: "Bharti Motwani",
  price: "$758",
  genre: "cse",
 },
 {
  id: 24,
  img: "https://m.media-amazon.com/images/I/616u6carGKL._SL1004_.jpg",
  title: "Letters To My Mother ",
  author: "Vikkas Arun Pareek ",
  price: "$344",
  genre: "relationship"
 },
 {
  id: 25,
  img: "https://m.media-amazon.com/images/I/61RwOQ8w3DL._SL1400_.jpg",
  title: "Everything I Never Told You",
  author: "Ajay K Pandey",
  price: "$300.00",
  genre: "romance"
 },
 {
  id: 26,
  img: "https://m.media-amazon.com/images/I/71iJfuxXXJL._SL1000_.jpg",
  title: "When I Am With You",
  author: "Durjoy Dutta",
  price: "$155",
  genre: "romance"
 },
 {
  id: 27,
  img: "https://m.media-amazon.com/images/I/712NTPEWj6L._SY522_.jpg",
  title: "Emgineering Mathematics",
  author: "Ravish R Singh & Mukul Bhatt",
  price: "$230",
  genre: "maths"
 },
 {
   id: 28,
   img: "https://m.media-amazon.com/images/I/51quyzxh4wL._SY522_.jpg",
   title: "Calculus, Vol II, 2ed, An Indian Adaptation",
   author: "Tom M. Apostol",
   price: "$676",
   genre: "maths"
 },
 {
  id: 29,
  img: "https://m.media-amazon.com/images/I/91PQFpYWLwL._SL1500_.jpg",
  title: "Something I Never Told You",
  author: "Shravya Bhinder",
  price: "$194",
  genre: "romcom",
 },
 {
   id: 30,
   img: "https://m.media-amazon.com/images/I/51G8FJpXi2L._SY522_.jpg",
   title: "Differential Calculus For Begginers",
   author: "Joseph Edwards",
   price: "$229",
   genre: "maths",
 },
 {
  id: 31,
  img: "https://m.media-amazon.com/images/I/81vYY3LjpOL._SY522_.jpg",
  title: "Until Love Sets US Apart",
  author: " Aditya Nighhot",
  price: "$731",
  genre: "emotion",
 },
 {
  id: 34,
  img: "https://m.media-amazon.com/images/I/513EYdG56TL.jpg",
  title: "Love A Little Stronger",
  author: "Preeti Shenoy",
  price: "$1805",
  genre: "romance",
 },
 {
  id: 35,
  img: "https://m.media-amazon.com/images/I/71j8fwHoesL._SY522_.jpg",
  title: "Wake Up, Life is Calling",
  author: "Preeti Shenoy",
  price: " $421",
  genre: "motivation",
 },
 {
  id: 36,
  img: "https://m.media-amazon.com/images/I/71jbVr5srqL._SY522_.jpg",
  title: "Infinite Powers: The Story of Calculus",
  author: "Steven Strogatz",
  price: "$1,119",
  genre: "maths",
 },
 {
  id: 37,
  img: "https://m.media-amazon.com/images/I/61-nvchIH7L._SY522_.jpg",
  title: "First Love",
  author: "Sheeja Jose",
  price: "$88",
  genre: "romcom",
 },
 {
  id: 38,
  img: "https://m.media-amazon.com/images/I/51n6wnr0ANL._SY522_.jpg",
  title: "Integral Calculus For Beginners",
  author: "Joseph Edwards",
  price: "$456",
  genre: "maths",
 },
 {
  id: 39,
  img: "https://m.media-amazon.com/images/I/814Qut+iwCL._SY522_.jpg",
  title: "Gift Me A New Beginning",
  author: "Arpit Vageria",
  price: "$500",
  genre: "motivation",
 },
  {
  id: 40,
  img: "https://m.media-amazon.com/images/I/718QOMOhIQL._SY522_.jpg",
  title: "Better Than Best Friends",
  author: "Ahona Sadhu",
  price: "$48",
  genre: "romcom",
 },
 {
  id: 41,
  img: "https://m.media-amazon.com/images/I/91fimvIrIJL._SY522_.jpg",
  title: "Be My Perfect Ending",
  author: "Arpit Vageria",
  price: "$1,169",
  genre: "emotion"
 },
 {
  id: 43,
  img: "https://m.media-amazon.com/images/I/7118T-Ce1gL._SY522_.jpg",
  title: "It Was Always You",
  author: "Sudeep Nagarkar",
  price: "$126",
  genre: "romance",
 },
 {
  id: 44,
  img: "https://m.media-amazon.com/images/I/81dla6e8ecL._SY522_.jpg",
  title: "A Tale of Two Souls",
  author: "Anand Kumar",
  price: "$319",
  genre: "romance",
 },
 {
  id: 45,
  img: "https://m.media-amazon.com/images/I/71aCBltKcqL._SL1500_.jpg",
  title: "Our Non-fairy Tale Life",
  author: "Rooprashi",
  price: "$274",
  genre: "emotion"
 },
 {
  id: 46,
  img: "https://m.media-amazon.com/images/I/715-Ng237yL._SY522_.jpg",
  title: "The Match ǀ A feel good Romantic Comedy",
  author: "Sarah Adams",
  price: "$235",
  genre: "comedy",
 },
 {
  id: 47,
  img: "https://m.media-amazon.com/images/I/71pJzAAalLL._SY522_.jpg",
  title: "The Off Limits Rule",
  author: "Sarah Adams",
  price: "$94",
  genre: "romcom"
 },
 {
  id: 48,
  img: "https://m.media-amazon.com/images/I/71W7PrKJiuL._SY522_.jpg",
  title: "The Roommate Situation",
  author: "Katie Bailey",
  price: "$507",
  genre: "comedy",
 },
 {
  id: 49,
  img: "https://m.media-amazon.com/images/I/71NpHQt-SmL._SY522_.jpg",
  title: "The Law of Attraction",
  author: "Laura Carter",
  price: "$99",
  genre: "comedy",
 },
 {
  id: 50,
  img: "https://m.media-amazon.com/images/I/81RkPGyExnL._SY522_.jpg",
  title: "Mrs Funnybones",
  author: "Twinkle Khanna",
  price: "$42",
  genre: "comedy",
 },
 {
  id: 51,
  img: "https://m.media-amazon.com/images/I/91qI0Qv7z7L._SY522_.jpg",
  title: "The Khandavaprastha Conspiracy",
  author: "Christopher C. Doyle",
  price: "$399",
  genre: "thriller",
 },
 {
  id: 52,
  img: "https://m.media-amazon.com/images/I/81e+mSqZvnL._SY522_.jpg",
  title: "Where the Crawdads Sing",
  author: "Delia Owens",
  price: "$948",
  genre: "thriller",
 },
 {
  id: 53,
  img: "https://m.media-amazon.com/images/I/91sg6N81vBL._SY522_.jpg",
  title: "The Mysteries of the Universe",
  author: "Will Gater",
  price: "$96",
  genre: "universe",
 },
 {
  id: 54,
  img: "https://m.media-amazon.com/images/I/61kIoBofsoL._SY522_.jpg",
  title: "The Universe Always Has a Plan",
  author: "Matt Kahn",
  price: "$2,056",
  genre: "universe",
 },
 {
  id: 55,
  img: "https://m.media-amazon.com/images/I/81CxFvSNzYL._SY522_.jpg",
  title: "Holding Up the Universe",
  author: "Jennifer Niven",
  price: "$67",
  genre: "universe",
 },
 {
  id: 56,
  img: "https://m.media-amazon.com/images/I/91wUFiHq0zL._SY522_.jpg",
  title: "Vishwadarshan A Glimpse of the Universe",
  author: " Mahatma Ramratna Thapaliyal",
  price: "$256.23",
  genre: "universe",
 },
 {
  id: 57,
  img: "https://m.media-amazon.com/images/I/71LG891mA+L._SY522_.jpg",
  title: "Fault Lines: How Hidden Fractures Still Threaten the World Economy",
  author: " Raghuram Rajan",
  price: "$1,373",
  genre: "finance",
 },
 {
  id: 58,
  img: "https://m.media-amazon.com/images/I/61ASC42GPpL._SY522_.jpg",
  title: "Financial Intelligence",
  author: "Income Mastery",
  price: "$12.73",
  genre: "finance",
 },
 {
  id: 59,
  img: "https://m.media-amazon.com/images/I/61NNay67odL._SY522_.jpg",
  title: "You are the Best Wife: A True Love Story ",
  author: "Ajay K Pandey",
  price: "40.01",
  genre: "romance",
 },
 {
  id: 60,
  img: "https://m.media-amazon.com/images/I/61B84NiWabL._SY522_.jpg",
  title: "Think And Grow Rich ",
  author: "Napoleon Hill",
  price: "$803",
  genre: "finance",
 },
 {
  id: 61,
  img: "https://m.media-amazon.com/images/I/810SWrNkUsL._SY522_.jpg",
  title: "No Matter What I will always love you!",
  author: " Rohit Dawesar",
  price: "$80",
  genre: "romance",
 },
 {
  id: 62,
  img: "https://m.media-amazon.com/images/I/71rx8KjwhDL._SY522_.jpg",
  title: "Anger Management",
  author: "Ajay Bisaria",
  price: "$100",
  genre: "self development",
 },
 {
  id: 63,
  img: "https://m.media-amazon.com/images/I/61jCkOVf1oL._SY522_.jpg",
  title: "Do It Today: Overcome procrastination, improve productivity",
  author: "Darius Foroux",
  price: "$49",
  genre: "self development",
 },
 {
  id: 64,
  img: "https://m.media-amazon.com/images/I/81QOMjpuQpL._SY522_.jpg",
  title: "TWELFTH FAIL",
  author: "Anurag Phatak",
  price: "$178.00",
  genre: "inspiration",
 },
 {
  id: 65,
  img: "https://m.media-amazon.com/images/I/71CrTyKsazL._SY522_.jpg",
  title: "India Polity",
  author: "M LaxmiKanth",
  price: "$17.00",
  genre: "polity",
 },
 {
  id: 66,
  img: "https://m.media-amazon.com/images/I/814L+vq01mL._SY522_.jpg",
  title: "Ikigai",
  author: " Francesc Miralles",
  price: "$324",
  genre: "life",
 },
 {
  id: 67,
  img: "https://m.media-amazon.com/images/I/71PW5uQP26L._SY522_.jpg",
  title: "The Principles of Project Finance",
  author: " Rod Morrison",
  price: "$3,977",
  genre: "finance"
 },
 {
  id: 68,
  img: "https://m.media-amazon.com/images/I/71uF3XXrTyL._SY522_.jpg",
  title: "1947-1957, India: The Birth of a Republic",
  author: " Chandrachur Ghose",
  price: "$480",
  genre: "history",
 },
 {
  id: 69,
  img: "https://m.media-amazon.com/images/I/71YzcRpS3eL._SY522_.jpg",
  title: "Ancient and Medieval India",
  author: " Poonam Dalal Dahiya",
  price: "$680",
  genre: "history"
 },
 {
  id: 70,
  img: "https://m.media-amazon.com/images/I/71JUOvUtLXL._SY522_.jpg",
  title: "World History",
  author: "Wonder House Books",
  price: "$599",
  genre: "history",
 },
 {
  id: 71,
  img: "https://m.media-amazon.com/images/I/51KpaU-zz8L._SY522_.jpg",
  title: "Plant Ecology",
  author: "R .S. Ambasht",
  price: "$372",
  genre: "ecology",
 },
 {
  id: 72,
  img: "https://m.media-amazon.com/images/I/715u7p+38+L._SY522_.jpg",
  title: "7 Steps to living your best life",
  author: "Roxie Nafousi",
  price: "$381.04",
  genre: "life",
 },
 {
  id: 73, 
  img: "https://m.media-amazon.com/images/I/61WVRpAeALL._SY522_.jpg",
  title: "The Book Of Life",
  author: "J Krishnamurti",
  price: "$350",
  genre: "life",
 },
 {
  id: 74,
  img: "https://m.media-amazon.com/images/I/51SUF18MQdL._SX342_SY445_.jpg",
  title: "Science and Technology for UPSC",
  author: "Ravi P. Agrahari",
  price: "$613",
  genre: "civil service",
 },
 {
  id: 75, 
  img: "https://m.media-amazon.com/images/I/81mdG7rC-oL._SY522_.jpg",
  title: "You Can Heal Your Life",
  author: " Louise L. Hay",
  price: "$300",
  genre: "self development",
 },
 {
  id: 76, 
  img: "https://m.media-amazon.com/images/I/71XpkRq0ncL._SY522_.jpg",
  title: "Think Straight",
  author: "Darius Foroux",
  price: "$129",
  genre: "self development",
 },
 {
  id: 77, 
  img: "https://m.media-amazon.com/images/I/81IXVNS0uLL._SY522_.jpg",
  title: "Environment & Ecology",
  author: "R Rajagopalan",
  price: "$54",
  genre: "civil service",
 },
 {
  id: 78, 
  img: "https://m.media-amazon.com/images/I/81ZrVkKGSOL._SY522_.jpg",
  title: "Essentials of Medical Pharmacy",
  author: "K. D. Tripathi",
  price: "$323",
  genre: "medical"
 },
 {
  id: 79,
  img: "https://m.media-amazon.com/images/I/71YSSBS+rnL._SY522_.jpg",
  title: "Inventions and Discoveries Medical Inventions Knowledge Encyclopedia",
  author: "Wonder House Books",
  price: "$476",
  genre: "medical",
 },
 {
  id: 80,
  img: "https://m.media-amazon.com/images/I/61p87m3XHjL._SY522_.jpg",
  title: "Human Genetics",
  author: " Gangane",
  price: "$78",
  genre: "medical",
 },
 {
  id: 81,
  img: "https://m.media-amazon.com/images/I/81tcveWolIL._SY522_.jpg",
  title: "I Can Upon A Lighthouse",
  author: "Shantanu Naidu",
  price: "$8",
  genre: "short memoir",
 },
 {
  id: 82,
  img: "https://m.media-amazon.com/images/I/61bn7j8afoL._SY522_.jpg",
  title: "UI UX DESIGN AND FIGMA",
  author: "Rowe Thills",
  price: "$12",
  genre: "ui design",
 },
 {
  id: 83,
  img: "https://m.media-amazon.com/images/I/81aV6uopvpL._SY522_.jpg",
  title: "interior Designs",
  author: "Muamar Chang",
  price: "$68",
  genre: "interior design",
 },
 {
  id: 84,
  img: "https://m.media-amazon.com/images/I/81sle00HXXL._SY522_.jpg",
  title: "Interior Design for Beginners",
  author: "Alice Cussler",
  price: "$91.99",
  genre: "interior design",
 },
 {
  id: 85,
  img: "https://m.media-amazon.com/images/I/811obl-mnnL._SY522_.jpg",
  title: "The Art of Racing in the Rain",
  author: "Garth Stein",
  price: "$29.68",
  genre: "short memoir",
 },
 {
  id: 86,
  img: "https://m.media-amazon.com/images/I/71O9vSgaW6L._SY522_.jpg",
  title: "Practice Makes Perfect",
  author: "Sarah Adams",
  price: "$844",
  genre: "romcom",
 },
 {
  id: 87,
  img: "https://m.media-amazon.com/images/I/81vsxew5gaL._SY522_.jpg",
  title: "The Language of Flowers",
  author: "Vanessa Diffenbaugh",
  price: "$15",
  genre: "self development",
 },
 {
  id: 88,
  img: "https://m.media-amazon.com/images/I/91LE4MaQ8xL._SY522_.jpg",
  title: "A Dog's Purpose",
  author: "W. Bruce Cameron",
  price: "$11",
  genre: "friendship",
 },
 {
  id: 89,
  img: "https://m.media-amazon.com/images/I/81GKtlBkjNL._SY522_.jpg",
  title: "The Flower Code",
  author: "Laura Wolf",
  price: "$50.00",
  genre: "self development"
 },
 {
  id: 90,
  img: "https://m.media-amazon.com/images/I/61HeGIigLdL._SY522_.jpg",
  title: "Be Your Own Sunshine",
  author: "James Allen",
  price: "$12",
  genre: "self help",
 },
 {
  id: 91,
  img: "https://m.media-amazon.com/images/I/71hYussXYfL._SY522_.jpg",
  title: "The Magical Adventure Journey Of the Fairy",
  author: "Diana Molly",
  price: "$94",
  genre: "friendship",
 },
 {
  id: 92,
  img: "https://m.media-amazon.com/images/I/81m8wslclKL._SY522_.jpg",
  title: "Chewy Finds Friendship",
  author: "R Williams",
  price: "60.00",
  genre: "friendship",
 },
 {
  id: 93,
  img: "https://m.media-amazon.com/images/I/919yRHWgz7S._SY522_.jpg",
  title: "Birds, Bees & Blossoms",
  author: "Harriet de Winton",
  price: "$10.00",
  genre: "photography"
 },
 {
  id: 94,
  img: "https://m.media-amazon.com/images/I/71bAWHGBO2L._SY522_.jpg",
  title: "Between Us",
  author: "Mhairi McFarlane",
  price: "$88",
  genre: "romcom",
 },
 {
  id: 95,
  img: "https://m.media-amazon.com/images/I/81Yw0lkG8OL._SY522_.jpg",
  title: "The Story of Tata",
  author: " Peter Casey",
  price: "$579",
  genre: "biography",
 },
 {
  id: 96,
  img: "https://m.media-amazon.com/images/I/71ZUnzkEwQL._SY522_.jpg",
  title: "University of Berkshire Hathaway",
  author: "Daniel Pecaut",
  price: "$26",
  genre: "biography",
 },
 {
  id: 97,
  img: "https://m.media-amazon.com/images/I/51Xg3t40ZEL._SY445_SX342_.jpg",
  title: " A Guide to Decorating on a Budget",
  author: "Alice Cussler",
  price: "$19",
  genre: "interior design",
 },
 {
  id: 98,
  img: "https://m.media-amazon.com/images/I/81QhU2AT3aL._SY522_.jpg",
  title: "The Language of Flowers",
  author: " Nicolae Tanase",
  price: "$74",
  genre: "timeless meaning",
 },
 {
  id: 99,
  img: "https://m.media-amazon.com/images/I/71QZpKfi7XL._SY522_.jpg",
  title: "An Incomplete Life",
  author: "Vijaypat Singhania",
  price: "$38",
  genre: "biography",
 },
 {
  id: 100,
  img: "https://m.media-amazon.com/images/I/716f57zYnvL._SY522_.jpg",
  title: "The Pursuit of Happiness",
  author: "Daniel G. Brinton",
  price: "$114",
  genre: "self help",
 },
 {
  id: 101,
  img: "https://m.media-amazon.com/images/I/71SsDuRhMDL._SY522_.jpg",
  title: "Timmy' friendship, laughter, joy on the whimsical Land of Gigglington",
  author: "Farhad Shahzad Bhatti",
  price: "$1,147",
  genre: "friendship",
 },
 {
  id: 102,
  img: "https://m.media-amazon.com/images/I/81vsxew5gaL._SY522_.jpg",
  title: "The Language of Flowers",
  author: "Vanessa Diffenbaugh",
  price: "$157",
  genre: "family",
 },
 {
  id: 103,
  img: "https://m.media-amazon.com/images/I/81Q3AXgSzNL._SY522_.jpg",
  title: "The Complete Language of Flowers",
  author: "S. Theresa Dietz",
  price: "$1,420",
  genre: "family",
 },
 {
  id: 104,
  img: "https://m.media-amazon.com/images/I/81lTksXt4EL._SY522_.jpg",
  title: "Positive Parenting, Smart Parenting",
  author: "Tinat Atifa Masood",
  price: "$40",
  genre: "family",
 },
 {
  id: 105,
  img: "https://m.media-amazon.com/images/I/71ZRES19gpL._SY522_.jpg",
  title: "April",
  author: "Yagnya",
  price: "$82",
  genre: "romcom",
 },
 {
  id: 106,
  img: "https://m.media-amazon.com/images/I/611MuPL-MHL._SY522_.jpg",
  title: "Princess With A Wish",
  author: "Dhivya Bharathi",
  price: "$25",
  genre: "family",

 }
]
 